server:
  port: 8081

spring:
  application:
    name: config-server
  profiles:
    active: jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/spring_config
    username: root
    password: root@123
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT PROPERTIES.KY, PROPERTIES.VAL from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
          order: 0